// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkh8YT9jphm0iWN6J_6PiJvGfhn80MzXM',
    appId: '1:269497763950:web:8f158ee8d7878572c47e7f',
    messagingSenderId: '269497763950',
    projectId: 'capsto-6d350',
    authDomain: 'capsto-6d350.firebaseapp.com',
    storageBucket: 'capsto-6d350.appspot.com',
    measurementId: 'G-ZDKGMMLJ61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE0wNaqG32LEPn7oKl6c3ygzoGhTNLd7w',
    appId: '1:269497763950:android:92ebdc90b1e4560dc47e7f',
    messagingSenderId: '269497763950',
    projectId: 'capsto-6d350',
    storageBucket: 'capsto-6d350.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe6p9KnbIy-FMFdaEY3GnEbsRPT_6By7w',
    appId: '1:269497763950:ios:e35932c99250594cc47e7f',
    messagingSenderId: '269497763950',
    projectId: 'capsto-6d350',
    storageBucket: 'capsto-6d350.appspot.com',
    androidClientId: '269497763950-atm43djoiu9qh91cja4ieb595hs0ptn8.apps.googleusercontent.com',
    iosClientId: '269497763950-5p83chfqgke0ls81lntqddqai0g35qcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.zjfCapstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe6p9KnbIy-FMFdaEY3GnEbsRPT_6By7w',
    appId: '1:269497763950:ios:6bbb45cc6107520ec47e7f',
    messagingSenderId: '269497763950',
    projectId: 'capsto-6d350',
    storageBucket: 'capsto-6d350.appspot.com',
    androidClientId: '269497763950-atm43djoiu9qh91cja4ieb595hs0ptn8.apps.googleusercontent.com',
    iosClientId: '269497763950-dajrfq60n1jm3tj1kfuuqrn8ems1oqp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.zjfCapstone.RunnerTests',
  );
}
